---
name: message_app
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.10.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^4.3.2+4
  intl: ^0.16.1
  animations: ^1.1.2
  tuple: ^1.0.3
  flushbar: ^1.10.4
  cloud_firestore: ^0.16.0
  firebase_core: ^0.7.0
  linkify: ^3.0.0
  url_launcher: ^5.7.10
  flutter_link_preview: ^1.5.6
  cached_network_image: ^2.5.0
  firebase_auth: ^0.20.0+1
  sms_autofill: ^1.2.7
  shared_preferences: ^0.5.12+4
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  fonts:
  - family: Lato
    fonts:
    - asset: fonts/Roboto-Regular.ttf
    - asset: fonts/Roboto-Bold.ttf
      weight: 700
    - asset: fonts/Roboto-Medium.ttf
      weight: 500
    - asset: fonts/Roboto-Light.ttf
      weight: 300
  - family: Poppins
    fonts:
    - asset: fonts/Poppins-Regular.ttf
    - asset: fonts/Poppins-Medium.ttf
      weight: 500
