name: "TODO to Issue workflow"
on: ["push"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: TODO to Issue
        id: "todo"
        uses: alstr/todo-to-issue-action@v2.4.1
        with:
          REPO: ${{ github.repository }}
          BEFORE: ${{ github.event.before }}
          SHA: ${{ github.sha }}
          TOKEN: ${{ secrets.TODO_TOKEN }}
          LABEL: "// TODO:"
          COMMENT_MARKER: "//"